global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'scrapper_app'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: [ 'scrapper:8090' ]
  - job_name: 'bot_app'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: [ 'bot:8091' ]
