app:
  test: Scrapper
  scheduler:
    interval: 10s
  api:
    github-api-url: https://api.github.com
    stack-overflow-api-url: https://api.stackexchange.com/2
    bot-api-url: http://localhost:8081

spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    password: postgres
    username: postgres

springdoc:
  swagger-ui:
    path: /swagger-ui
