app:
  scheduler:
    interval: 1m
    update-batch-size: 5
  api:
    github-api-url: https://api.github.com
    stack-overflow-api-url: https://api.stackexchange.com/2.3
    bot-api-url: ${APP_BOT_API_URL}
  rabbit-mq:
    queue-name: links
    topic-exchange-name: links-topic-exchange
    links-routing-key: links

  database-access-type: jooq
  bot-update-sender-type: rabbitmq

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: ${APP_POSTGRES_JDBC_URL}
    password: postgres
    username: postgres
  rabbitmq:
    host: ${APP_RABBITMQ_HOST}
    port: 5672
    password: rabbitmq
    username: rabbitmq

management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: info, health, prometheus
      path-mapping:
        health: "health"
        prometheus: "metrics"
    enabled-by-default: false

  metrics:
    tags:
      application: ${spring.application.name}

  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true

  server:
    port: 8090

springdoc:
  swagger-ui:
    path: /swagger-ui
