app:
  scheduler:
    interval: 30s
    update-batch-size: 5
  api:
    github-api-url: https://api.github.com
    stack-overflow-api-url: https://api.stackexchange.com/2.3
    bot-api-url: http://localhost:8081
  rabbit-mq:
    queue-name: links
    topic-exchange-name: links-topic-exchange

  database-access-type: jooq

spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    password: postgres
    username: postgres

springdoc:
  swagger-ui:
    path: /swagger-ui
