{
 "title": "Argus dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Application", "query": "bot,scrapper" }
  ]
 },
 "panels": [
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Processed messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(app_processed_messages_counter_total[60s]) * 60",
     "legendFormat": "messages"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_sum{application=\"$Application\"}[1m])) / sum by (uri) (rate(http_server_requests_seconds_count{application=\"$Application\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "JVM Memory allocation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$Application\", area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "GC Memory allocation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{application=\"$Application\"}[1m])",
     "legendFormat": "allocated memory"
    }
   ]
  }
 ]
}