app:
  bot:
    apiKey: ${APP_TELEGRAM_KEY}
  api:
    scrapperApiUrl: 'http://localhost:8080'
  scrapper-queue:
    name: links
    dlq-name: ${app.scrapper-queue.name}.dlq

server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    password: rabbitmq
    username: rabbitmq
    listener:
      simple:
        default-requeue-rejected: false

management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        health: "health"
        prometheus: "metrics"
    enabled-by-default: false

  metrics:
    tags:
      application: ${spring.application.name}

  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true

  server:
    port: 8091

springdoc:
  swagger-ui:
    path: /swagger-ui
