app:
  bot:
    apiKey: ${APP_TELEGRAM_KEY}
  api:
    scrapperApiUrl: 'http://localhost:8080'
  scrapper-queue:
    name: links
    dlq-name: ${app.scrapper-queue.name}.dlq

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  rabbitmq:
    host: localhost
    password: rabbitmq
    username: rabbitmq
    listener:
      simple:
        default-requeue-rejected: false

server:
  port: 8081
