services:
  postgresql:
    container_name: postgres_container
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scrapper
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - backend
    ports:
      - "5432:5432"
  liquibase-migrations:
    container_name: liquibase_container
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

volumes:
  postgres:

networks:
  backend:
