name: Bot workflow

on:
  push:
    paths:
      - '.github/workflows/bot.yml'
      - 'bot/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: argus-bot-image
  DOCKERFILE_PATH: bot.Dockerfile

permissions:
  contents: read
  packages: write

jobs:
  checkstyle:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
      - uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: Check formatting
        run: mvn -pl ./bot -am checkstyle:check

  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
      - uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: Build
        run: mvn package -pl ./bot -am -B

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
