name: Bot workflow

on:
  push:
    paths:
      - 'bot/**'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
      - uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: Build
        run: mvn package -pl ./bot -am -B
