name: Scrapper workflow

on:
  push:
    paths:
      - 'scrapper/**'
      - 'scrapper-jooq/**'
      - 'link-parser/**'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
      - uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: Generate Jooq classes
        run: |
          mvn package -pl ./scrapper-jooq -B
          java -jar ./scrapper-jooq/target/scrapper-jooq-1.0.jar
      - name: Build
        run: mvn package -pl ./scrapper -am -B
